// Code generated by framework. DO NOT EDIT.

package framework

import (
	"github.com/gofiber/fiber/v2"
	api "playground/app/api"
	dashboard "playground/app/pages/dashboard"
	gonx_app_pages "playground/gonx/app/pages"
	gonx_app_pages_dashboard "playground/gonx/app/pages/dashboard"
	gonx_app_pages_dashboard_form "playground/gonx/app/pages/dashboard/form"
	gonx_app_pages_hello "playground/gonx/app/pages/hello"
	gonx_app_pages_user__id "playground/gonx/app/pages/user/_id"
	gonx_app_pages_user_edit "playground/gonx/app/pages/user/edit"
)

func RegisterRoutes(router *fiber.App) {
	router.Get("/", gonx_app_pages.Index)
	router.Delete("/api/dashboard", dashboard.Delete)
	router.Get("/api/dashboard", dashboard.Get)
	router.Post("/api/dashboard", dashboard.Post)
	router.Put("/api/dashboard", dashboard.Put)
	router.Get("/api/hello", api.GetHello)
	router.Get("/dashboard/form", gonx_app_pages_dashboard_form.Index)
	router.Get("/dashboard", gonx_app_pages_dashboard.Index)
	router.Get("/hello", gonx_app_pages_hello.Index)
	router.Get("/user/edit", gonx_app_pages_user_edit.Get)
	router.Get("/user/:id", gonx_app_pages_user__id.Index)
	router.Use(NotFound)
}

func NotFound(c *fiber.Ctx) error {
	c.Status(fiber.StatusNotFound)
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(`<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>404 - Pagina nao encontrada</title>
	<style>
		* { margin: 0; padding: 0; box-sizing: border-box; }
		body {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
			font-family: system-ui, -apple-system, sans-serif;
			background: #ffffff;
			color: #1f2937;
		}
		.container { text-align: center; }
		.container h1 { font-size: 6rem; font-weight: 700; color: #e5e7eb; margin-bottom: 1rem; }
		.container p { font-size: 1.25rem; color: #6b7280; }
	</style>
</head>
<body>
	<div class="container">
		<h1>404</h1>
		<p>Pagina nao encontrada</p>
	</div>
</body>
</html>`)
}
