// Code generated by gonx. DO NOT EDIT.

package layouts

import (
	"io"
	"fmt"
	"html"
)

func RenderFull(w io.Writer, title string, children func(io.Writer)) {
	io.WriteString(w, "<!DOCTYPE html>\n<html lang=\"pt-BR\">\n<head>\n\t<meta charset=\"UTF-8\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\t<title>")
	io.WriteString(w, html.EscapeString(fmt.Sprintf("%v", title)))
	io.WriteString(w, "</title>\n\t<script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js\"></script>\n\t<link rel=\"stylesheet\" href=\"/styles.css\"/>\n</head>\n<body class=\"bg-gray-900 text-white min-h-screen\">\n\t<div class=\"flex flex-col h-screen\">\n\t\t<header class=\"bg-gray-800 p-4 border-b border-gray-700\">\n\t\t\t<h1 class=\"text-xl font-bold\">Full Layout Mode</h1>\n\t\t</header>\n\t\t<main class=\"flex-1 overflow-auto p-8\">\n\t\t\t")
	children(w)
	io.WriteString(w, "\n\t\t</main>\n\t</div>\n</body>\n</html>")
}

