// Code generated by gonx. DO NOT EDIT.

package layouts

import (
	"io"
	"fmt"
	"html"
)

func RenderIndex(w io.Writer, title string, children func(io.Writer)) {
	io.WriteString(w, "<!DOCTYPE html>\n<html lang=\"pt-BR\">\n<head>\n\t<meta charset=\"UTF-8\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\t<title>")
	io.WriteString(w, html.EscapeString(fmt.Sprintf("%v", title)))
	io.WriteString(w, "</title>\n\t<script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js\" integrity=\"sha384-H5SrcfygHmAuTDZphMHqBJLc3FhssKjG7w/CeCpFReSfwBWDTKpkzPP8c+cLsK+V\" crossorigin=\"anonymous\"></script>\n\t<link rel=\"stylesheet\" href=\"/styles.css\"/>\n</head>\n<body class=\"bg-gray-50 text-gray-900 min-h-screen\">\n\t<main class=\"container mx-auto px-4 py-8\">\n\t\t")
	children(w)
	io.WriteString(w, "\n\t</main>\n</body>\n</html>")
}

