// Code generated by gonx. DO NOT EDIT.

package edit

import (
	"io"
	"github.com/gofiber/fiber/v2"
	"playground/gonx/app/layouts"
	"strconv"
	"playground/app/models"
)

func Get(c *fiber.Ctx) error {
	id, _ := strconv.Atoi(c.Query("id"))
	u, ok := models.FindUserByID(id)
	if !ok {
		return c.Status(fiber.StatusNotFound).SendString("User not found")
	}
	c.Type("html")
	models.RenderUserEditForm(c.Response().BodyWriter(), u)
	return nil
}

func RenderIndex(w io.Writer, c *fiber.Ctx) {
}

func Index(c *fiber.Ctx) error {
	w := c.Response().BodyWriter()
	c.Set("Content-Type", "text/html; charset=utf-8")
	layouts.RenderIndex(w, "Go Framework", func(w io.Writer) {
		RenderIndex(w, c)
	})
	return nil
}

