package gonx

import (
	"fmt"
	"regexp"
	"strings"
)

// Compiler compila o template .gonx em código Go
type Compiler struct {
	pf           *ParsedFile
	usesFmt      bool
	usesHtml     bool
	usesIO       bool
	usesNetHttp  bool
}

func NewCompiler(pf *ParsedFile) *Compiler {
	return &Compiler{pf: pf}
}

// Compile gera o código Go completo para o arquivo
func (c *Compiler) Compile() (string, error) {
	var b strings.Builder

	// Package
	b.WriteString("// Code generated by gonx. DO NOT EDIT.\n\n")
	b.WriteString("package " + c.pf.Package + "\n\n")

	// Gera o corpo primeiro para saber quais imports são necessários
	var body strings.Builder
	for _, fn := range c.pf.Funcs {
		if err := c.compileFunc(&body, fn); err != nil {
			return "", fmt.Errorf("erro ao compilar função %s: %w", fn.Name, err)
		}
	}

	// Monta os imports
	imports := c.buildImports()
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	// Escreve o corpo
	b.WriteString(body.String())

	return b.String(), nil
}

func (c *Compiler) buildImports() []string {
	var imports []string
	
	// Sempre precisa de io (writer)
	imports = append(imports, `"io"`)
	
	if c.usesFmt {
		imports = append(imports, `"fmt"`)
	}
	if c.usesHtml {
		imports = append(imports, `"html"`)
	}
	if c.usesNetHttp {
		imports = append(imports, `"net/http"`)
	}
	
	// Imports explícitos do usuário
	imports = append(imports, c.pf.Imports...)
	
	// Auto-imports descobertos
	imports = append(imports, c.pf.AutoImports...)
	
	// Remove duplicatas
	seen := make(map[string]bool)
	var unique []string
	for _, imp := range imports {
		if !seen[imp] {
			seen[imp] = true
			unique = append(unique, imp)
		}
	}
	
	return unique
}

func (c *Compiler) compileFunc(b *strings.Builder, fn FuncSignature) error {
	funcName := fn.Name
	renderName := "Render" + funcName
	
	isHTTPHandler := strings.Contains(fn.Params, "http.ResponseWriter") && strings.Contains(fn.Params, "*http.Request")
	renderParams := fn.Params
	if isHTTPHandler {
		renderParams = ""
		c.usesNetHttp = true
	}
	
	b.WriteString(fmt.Sprintf("func %s(w io.Writer", renderName))
	if renderParams != "" {
		b.WriteString(", " + renderParams)
	}
	b.WriteString(") {\n")

	if err := c.compileTemplateBody(b, c.pf.Template, 1); err != nil {
		return err
	}

	b.WriteString("}\n\n")

	if fn.ReturnType == "" && isHTTPHandler {
		b.WriteString(fmt.Sprintf("func %sHandler(w http.ResponseWriter, r *http.Request) {\n", funcName))
		b.WriteString(fmt.Sprintf("\t%s(w)\n", renderName))
		b.WriteString("}\n\n")
	}

	return nil
}

func (c *Compiler) compileTemplateBody(b *strings.Builder, tmpl string, indent int) error {
	tabs := strings.Repeat("\t", indent)
	
	re := regexp.MustCompile(`(?s)\{\{\s*(.*?)\s*\}\}`)
	
	lastIndex := 0
	matches := re.FindAllStringSubmatchIndex(tmpl, -1)
	
	for _, m := range matches {
		if m[0] > lastIndex {
			text := tmpl[lastIndex:m[0]]
			if strings.TrimSpace(text) != "" {
				b.WriteString(tabs + c.writeString(text))
			}
		}
		
		expr := tmpl[m[2]:m[3]]
		if err := c.compileExpr(b, strings.TrimSpace(expr), indent); err != nil {
			return err
		}
		
		lastIndex = m[1]
	}
	
	if lastIndex < len(tmpl) {
		text := tmpl[lastIndex:]
		if strings.TrimSpace(text) != "" {
			b.WriteString(tabs + c.writeString(text))
		}
	}
	
	return nil
}

func (c *Compiler) compileExpr(b *strings.Builder, expr string, indent int) error {
	tabs := strings.Repeat("\t", indent)
	
	// Controle de fluxo
	if strings.HasPrefix(expr, "if ") {
		cond := strings.TrimPrefix(expr, "if ")
		b.WriteString(tabs + "if " + cond + " {\n")
		return nil
	}
	if expr == "else" {
		b.WriteString(tabs + "} else {\n")
		return nil
	}
	if expr == "end" {
		b.WriteString(tabs + "}\n")
		return nil
	}
	
	if strings.HasPrefix(expr, "range ") {
		items := strings.TrimPrefix(expr, "range ")
		b.WriteString(tabs + "for _, _gonx_it := range " + items + " {\n")
		return nil
	}
	
	// É uma expressão de valor -> precisa de fmt e html
	c.usesFmt = true
	
	needsEscape := !strings.Contains(expr, ".Raw") && !strings.HasPrefix(expr, "html.")
	
	if needsEscape {
		c.usesHtml = true
		b.WriteString(tabs + fmt.Sprintf("io.WriteString(w, html.EscapeString(fmt.Sprintf(\"%%v\", %s)))\n", expr))
	} else {
		if strings.HasPrefix(expr, "html.") {
			expr = strings.TrimPrefix(expr, "html.")
		}
		if strings.Contains(expr, ".Raw") {
			expr = strings.Replace(expr, ".Raw", "", -1)
		}
		b.WriteString(tabs + fmt.Sprintf("io.WriteString(w, fmt.Sprintf(\"%%v\", %s))\n", expr))
	}
	
	return nil
}

func (c *Compiler) writeString(text string) string {
	escaped := strings.ReplaceAll(text, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, "\n", `\n`)
	escaped = strings.ReplaceAll(escaped, "\t", `\t`)
	
	return fmt.Sprintf("io.WriteString(w, \"%s\")\n", escaped)
}
