package gonx

import (
	"fmt"
	"regexp"
	"strings"
)

// Compiler compila o template .gonx em código Go
type Compiler struct {
	pf          *ParsedFile
	usesFmt     bool
	usesHtml    bool
	usesIO      bool
	usesFiber   bool
	usesLayout  bool
	usesComponents bool
	blockStack  []string
	Minify      bool
}

func NewCompiler(pf *ParsedFile) *Compiler {
	return &Compiler{pf: pf}
}

// Compile gera o código Go completo para o arquivo
func (c *Compiler) Compile() (string, error) {
	var b strings.Builder

	// Package
	b.WriteString("// Code generated by gonx. DO NOT EDIT.\n\n")
	b.WriteString("package " + c.pf.Package + "\n\n")

	// Gera o corpo primeiro para saber quais imports são necessários
	var body strings.Builder

	c.usesComponents = strings.Contains(c.pf.Template, "call components.")

	if c.pf.IsPage {
		if err := c.compilePage(&body); err != nil {
			return "", err
		}
	} else {
		if err := c.compileAPI(&body); err != nil {
			return "", err
		}
	}

	// Monta os imports
	imports := c.buildImports()
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}

	// Escreve o corpo
	b.WriteString(body.String())

	return b.String(), nil
}

func (c *Compiler) buildImports() []string {
	var imports []string

	if c.usesIO {
		imports = append(imports, `"io"`)
	}

	if c.usesFmt {
		imports = append(imports, `"fmt"`)
	}
	if c.usesHtml {
		imports = append(imports, `"html"`)
	}
	if c.usesFiber {
		imports = append(imports, `"github.com/gofiber/fiber/v2"`)
	}
	if c.usesLayout {
		moduleName := c.pf.ModuleName()
		imports = append(imports, fmt.Sprintf(`"%s/gonx/app/layouts"`, moduleName))
	}
	// Adiciona components se houver diretivas ou uso provável
	// Pula se já estiver no pacote components ou se não for usado
	if c.pf.Package != "components" && c.usesComponents {
		moduleName := c.pf.ModuleName()
		imports = append(imports, fmt.Sprintf(`"%s/gonx/app/components"`, moduleName))
	}

	// Imports explícitos do usuário
	imports = append(imports, c.pf.Imports...)

	// Auto-imports descobertos
	imports = append(imports, c.pf.AutoImports...)

	// Remove duplicatas
	seen := make(map[string]bool)
	var unique []string
	for _, imp := range imports {
		if !seen[imp] {
			seen[imp] = true
			unique = append(unique, imp)
		}
	}

	return unique
}

// compilePage gera código para arquivos em app/pages/
// - Inclui funções com corpo do script
// - Gera Render<PageName> para o template
// - Gera handler HTTP automaticamente
func (c *Compiler) compilePage(b *strings.Builder) error {
	// Inclui funções com corpo do script
	for _, fn := range c.pf.Funcs {
		if fn.HasBody && fn.BodySource != "" {
			b.WriteString(fn.BodySource + "\n\n")
		}
	}

	pageName := c.pf.PageName
	renderName := "Render" + pageName

	// Tenta encontrar o stub da função atual no script para pegar os parâmetros
	var stub *FuncSignature
	for _, fn := range c.pf.Funcs {
		if fn.Name == pageName && !fn.HasBody {
			stub = &fn
			break
		}
	}

	params := "w io.Writer, c *fiber.Ctx"
	if stub != nil && stub.Params != "" {
		if strings.Contains(stub.Params, "w io.Writer") {
			params = stub.Params
		} else {
			params = "w io.Writer, " + stub.Params
		}
	}

	// Gera Render<PageName>(w io.Writer, ...)
	c.usesIO = true
	if strings.Contains(params, "*fiber.Ctx") {
		c.usesFiber = true
	}
	b.WriteString(fmt.Sprintf("func %s(%s) {\n", renderName, params))
	if err := c.compileTemplateBody(b, autoInjectHTMX(c.pf.Template), 1); err != nil {
		return err
	}
	b.WriteString("}\n\n")

	// Pula geração de handler Fiber para layouts e components (não são rotas)
	if strings.Contains(c.pf.FilePath, "app/layouts/") || strings.Contains(c.pf.FilePath, "app/components/") {
		return nil
	}

	// Se o usuário já definiu um handler Get customizado, não geramos o handler padrão da página
	hasCustomGet := false
	for _, fn := range c.pf.Funcs {
		if fn.Name == "Get" {
			hasCustomGet = true
			break
		}
	}
	if hasCustomGet {
		return nil
	}

	// Gera handler Fiber
	c.usesFiber = true
	layout := c.findPageLayout()
	if layout != nil {
		c.usesLayout = true
		layoutCall := layout.LayoutPkg + ".Render" + layout.LayoutFunc
		b.WriteString(fmt.Sprintf("func %s(c *fiber.Ctx) error {\n", pageName))
		b.WriteString("\tw := c.Response().BodyWriter()\n")
		b.WriteString("\tc.Set(\"Content-Type\", \"text/html; charset=utf-8\")\n")
		if layout.LayoutArgs != "" {
			b.WriteString(fmt.Sprintf("\t%s(w, %s, func(w io.Writer) {\n", layoutCall, layout.LayoutArgs))
		} else {
			b.WriteString(fmt.Sprintf("\t%s(w, func(w io.Writer) {\n", layoutCall))
		}
		b.WriteString(fmt.Sprintf("\t\t%s(w, c)\n", renderName))
		b.WriteString("\t})\n")
		b.WriteString("\treturn nil\n")
		b.WriteString("}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("func %s(c *fiber.Ctx) error {\n", pageName))
		b.WriteString("\tw := c.Response().BodyWriter()\n")
		b.WriteString("\tc.Set(\"Content-Type\", \"text/html; charset=utf-8\")\n")
		b.WriteString(fmt.Sprintf("\t%s(w, c)\n", renderName))
		b.WriteString("\treturn nil\n")
		b.WriteString("}\n\n")
	}

	return nil
}

// findPageLayout procura uma função stub no script com o nome da página
// que tenha diretivas de layout
func (c *Compiler) findPageLayout() *FuncSignature {
	// Procura layout explícito no script
	for _, fn := range c.pf.Funcs {
		if fn.Name == c.pf.PageName && !fn.HasBody && fn.LayoutPkg != "" && fn.LayoutFunc != "" {
			return &fn
		}
	}

	// Fallback automático para layouts.Index se for uma página e não estiver em layouts ou components
	if !strings.Contains(c.pf.FilePath, "app/layouts/") && !strings.Contains(c.pf.FilePath, "app/components/") {
		return &FuncSignature{
			LayoutPkg:  "layouts",
			LayoutFunc: "Index",
			LayoutArgs: "\"Go Framework\"", // Título padrão
		}
	}

	return nil
}

// compileAPI gera código para arquivos em app/api/
func (c *Compiler) compileAPI(b *strings.Builder) error {
	// Inclui funções com corpo do script
	for _, fn := range c.pf.Funcs {
		if fn.HasBody && fn.BodySource != "" {
			b.WriteString(fn.BodySource + "\n\n")
		}
	}

	// Para cada stub HTTP handler, gera render + wrapper
	for _, fn := range c.pf.Funcs {
		if fn.HasBody {
			continue
		}
		if err := c.compileFunc(b, fn); err != nil {
			return err
		}
	}

	return nil
}

func (c *Compiler) compileFunc(b *strings.Builder, fn FuncSignature) error {
	funcName := fn.Name
	renderName := "Render" + funcName

	isHTTPHandler := strings.Contains(fn.Params, "http.ResponseWriter") || strings.Contains(fn.Params, "*fiber.Ctx")
	renderParams := fn.Params
	if isHTTPHandler {
		renderParams = ""
		c.usesFiber = true
	}

	c.usesIO = true
	b.WriteString(fmt.Sprintf("func %s(w io.Writer", renderName))
	if renderParams != "" {
		b.WriteString(", " + renderParams)
	}
	b.WriteString(") {\n")

	if err := c.compileTemplateBody(b, autoInjectHTMX(c.pf.Template), 1); err != nil {
		return err
	}

	b.WriteString("}\n\n")

	if fn.ReturnType == "" && isHTTPHandler {
		if fn.LayoutPkg != "" && fn.LayoutFunc != "" {
			layoutCall := fn.LayoutPkg + ".Render" + fn.LayoutFunc
			b.WriteString(fmt.Sprintf("func %s(c *fiber.Ctx) error {\n", funcName))
			b.WriteString("\tw := c.Response().BodyWriter()\n")
			b.WriteString("\tc.Set(\"Content-Type\", \"text/html; charset=utf-8\")\n")
			if fn.LayoutArgs != "" {
				b.WriteString(fmt.Sprintf("\t%s(w, %s, func(w io.Writer) {\n", layoutCall, fn.LayoutArgs))
			} else {
				b.WriteString(fmt.Sprintf("\t%s(w, func(w io.Writer) {\n", layoutCall))
			}
			b.WriteString(fmt.Sprintf("\t\t%s(w)\n", renderName))
			b.WriteString("\t})\n")
			b.WriteString("\treturn nil\n")
			b.WriteString("}\n\n")
		} else {
			b.WriteString(fmt.Sprintf("func %s(c *fiber.Ctx) error {\n", funcName))
			b.WriteString("\tw := c.Response().BodyWriter()\n")
			b.WriteString("\tc.Set(\"Content-Type\", \"text/html; charset=utf-8\")\n")
			b.WriteString(fmt.Sprintf("\t%s(w)\n", renderName))
			b.WriteString("\treturn nil\n")
			b.WriteString("}\n\n")
		}
	}
	return nil
}

func (c *Compiler) compileTemplateBody(b *strings.Builder, tmpl string, indent int) error {
	tabs := strings.Repeat("\t", indent)

	re := regexp.MustCompile(`(?s)\{\{\s*(.*?)\s*\}\}`)

	lastIndex := 0
	matches := re.FindAllStringSubmatchIndex(tmpl, -1)

	for _, m := range matches {
		if m[0] > lastIndex {
			text := tmpl[lastIndex:m[0]]
			if strings.TrimSpace(text) != "" {
				b.WriteString(tabs + c.writeString(text))
			}
		}

		expr := tmpl[m[2]:m[3]]
		if err := c.compileExpr(b, strings.TrimSpace(expr), indent); err != nil {
			return err
		}

		lastIndex = m[1]
	}

	if lastIndex < len(tmpl) {
		text := tmpl[lastIndex:]
		if strings.TrimSpace(text) != "" {
			b.WriteString(tabs + c.writeString(text))
		}
	}

	return nil
}

func (c *Compiler) compileExpr(b *strings.Builder, expr string, indent int) error {
	tabs := strings.Repeat("\t", indent)

	// Controle de fluxo
	if strings.HasPrefix(expr, "if ") {
		cond := strings.TrimPrefix(expr, "if ")
		b.WriteString(tabs + "if " + cond + " {\n")
		c.blockStack = append(c.blockStack, "if")
		return nil
	}
	if strings.HasPrefix(expr, "else if ") {
		cond := strings.TrimPrefix(expr, "else if ")
		b.WriteString(tabs + "} else if " + cond + " {\n")
		return nil
	}
	if expr == "else" {
		b.WriteString(tabs + "} else {\n")
		return nil
	}
	if expr == "end" {
		if len(c.blockStack) > 0 {
			last := c.blockStack[len(c.blockStack)-1]
			c.blockStack = c.blockStack[:len(c.blockStack)-1]
			if last == "call" {
				b.WriteString(tabs + "})\n")
			} else {
				b.WriteString(tabs + "}\n")
			}
		} else {
			b.WriteString(tabs + "}\n")
		}
		return nil
	}

	if strings.HasPrefix(expr, "range ") {
		items := strings.TrimPrefix(expr, "range ")
		b.WriteString(tabs + "for _, _gonx_it := range " + items + " {\n")
		c.blockStack = append(c.blockStack, "for")
		return nil
	}

	if strings.HasPrefix(expr, "call ") {
		call := strings.TrimPrefix(expr, "call ")
		c.blockStack = append(c.blockStack, "call")
		// Converte Package.Func para Package.RenderFunc ou Func para RenderFunc
		dotIdx := strings.LastIndex(call, ".")
		parenIdx := strings.Index(call, "(")
		if parenIdx == -1 {
			parenIdx = len(call)
		}

		if dotIdx != -1 && dotIdx < parenIdx {
			call = call[:dotIdx+1] + "Render" + call[dotIdx+1:]
		} else {
			call = "Render" + call
		}

		// Se tem parênteses, insere w antes deles. Se não, adiciona (w,
		if strings.Contains(call, "(") {
			call = strings.Replace(call, "(", "(w, ", 1)
			b.WriteString(tabs + fmt.Sprintf("%s, func(w io.Writer) {\n", strings.TrimSuffix(call, ")")))
		} else {
			b.WriteString(tabs + fmt.Sprintf("%s(w, func(w io.Writer) {\n", call))
		}
		return nil
	}

	// children é um slot especial: chama a função callback
	if expr == "children" {
		b.WriteString(tabs + "children(w)\n")
		return nil
	}

	// É uma expressão de valor -> precisa de fmt e html
	c.usesFmt = true
	c.usesIO = true

	needsEscape := !strings.Contains(expr, ".Raw") && !strings.HasPrefix(expr, "html.")

	if needsEscape {
		c.usesHtml = true
		b.WriteString(tabs + fmt.Sprintf("io.WriteString(w, html.EscapeString(fmt.Sprintf(\"%%v\", %s)))\n", expr))
	} else {
		if after, ok :=strings.CutPrefix(expr, "html."); ok  {
			expr = after
		}
		if strings.Contains(expr, ".Raw") {
			expr = strings.ReplaceAll(expr, ".Raw", "", )
		}
		b.WriteString(tabs + fmt.Sprintf("io.WriteString(w, fmt.Sprintf(\"%%v\", %s))\n", expr))
	}

	return nil
}

// autoInjectHTMX insere o script do HTMX local no <head> se ainda não estiver presente.
func autoInjectHTMX(tmpl string) string {
	lower := strings.ToLower(tmpl)
	// Só injeta se houver <head> e não houver referência ao htmx.min.js
	if !strings.Contains(lower, "<head") || strings.Contains(lower, "htmx.min.js") {
		return tmpl
	}

	// Procura o fim da tag de abertura <head> (com ou sem atributos)
	headOpenEnd := strings.Index(lower, "<head")
	if headOpenEnd == -1 {
		return tmpl
	}
	// Avança até o '>' correspondente
	for i := headOpenEnd; i < len(tmpl); i++ {
		if tmpl[i] == '>' {
			headOpenEnd = i + 1
			break
		}
	}

	script := "\n<script src=\"/htmx.min.js\"></script>"
	return tmpl[:headOpenEnd] + script + tmpl[headOpenEnd:]
}

func minifyHTMLFragment(text string) string {
	// 1. Remove comentários HTML (<!-- ... -->)
	reComment := regexp.MustCompile(`(?s)<!--.*?-->`)
	text = reComment.ReplaceAllString(text, "")

	// 2. Reduz múltiplos espaços em branco, quebras de linha e tabs a um único espaço
	reSpace := regexp.MustCompile(`\s+`)
	text = reSpace.ReplaceAllString(text, " ")

	// 3. Remove espaços ao redor de "=" nos atributos (ex: class = "foo" -> class="foo")
	reAttrEq := regexp.MustCompile(`\s*=\s*`)
	text = reAttrEq.ReplaceAllString(text, "=")

	// 4. Remove espaços antes de fechar a tag (ex: <div > -> <div>, <br /> -> <br/>)
	reBeforeClose := regexp.MustCompile(`\s+>`)
	text = reBeforeClose.ReplaceAllString(text, ">")
	reSelfClose := regexp.MustCompile(`\s+/>`)
	text = reSelfClose.ReplaceAllString(text, "/>")

	// 5. Minificação avançada: remove espaços ao redor de elementos de bloco.
	// É seguro remover o espaço antes e depois dessas tags, sem quebrar o fluxo de texto de elementos inline (como <span> ou <a>).
	blockTags := "html|head|body|div|p|h[1-6]|ul|ol|li|nav|header|footer|section|article|aside|main|table|tr|td|th|thead|tbody|tfoot|form|template|meta|link|svg|path|g|circle|rect|button"

	// Remove espaço antes da abertura/fechamento de uma tag de bloco: ` <div` -> `<div`, ` </div>` -> `</div>`
	reBlockBefore := regexp.MustCompile(`(?i)\s+<(/?(?:` + blockTags + `)\b)`)
	text = reBlockBefore.ReplaceAllString(text, "<$1")

	// Remove espaço depois da abertura/fechamento de uma tag de bloco: `<div> ` -> `<div>`, `</div> ` -> `</div>`
	reBlockAfter := regexp.MustCompile(`(?i)(<(/?(?:` + blockTags + `)\b[^>]*>))\s+`)
	text = reBlockAfter.ReplaceAllString(text, "$1")

	return strings.TrimSpace(text)
}

func (c *Compiler) writeString(text string) string {
	c.usesIO = true
	
	// Minifica o fragmento HTML apenas se solicitado (deixa o código inline e reduz o tamanho do bundle)
	if c.Minify {
		text = minifyHTMLFragment(text)
	}

	escaped := strings.ReplaceAll(text, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	escaped = strings.ReplaceAll(escaped, "\n", `\n`)
	escaped = strings.ReplaceAll(escaped, "\t", `\t`)

	return fmt.Sprintf("io.WriteString(w, \"%s\")\n", escaped)
}
