// Code generated by gonx. DO NOT EDIT.

package components

import (
	"io"
	"fmt"
	"html"
)

func RenderBadge(w io.Writer, color string, children func(io.Writer)) {
	io.WriteString(w, "<span class=\"inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-")
	io.WriteString(w, html.EscapeString(fmt.Sprintf("%v", color)))
	io.WriteString(w, "-100 text-")
	io.WriteString(w, html.EscapeString(fmt.Sprintf("%v", color)))
	io.WriteString(w, "-800\">\n\t")
	children(w)
	io.WriteString(w, "\n</span>")
}

