// Code generated by gonx. DO NOT EDIT.

package components

import (
	"io"
	"fmt"
	"html"
)

func RenderCard(w io.Writer, title string, children func(io.Writer)) {
	io.WriteString(w, "<div class=\"bg-white rounded-xl shadow-md hover:shadow-lg transition-shadow p-6 border border-gray-100\">\n\t<h3 class=\"text-lg font-semibold text-gray-800 mb-2\">")
	io.WriteString(w, html.EscapeString(fmt.Sprintf("%v", title)))
	io.WriteString(w, "</h3>\n\t<div class=\"text-gray-600\">\n\t\t")
	children(w)
	io.WriteString(w, "\n\t</div>\n</div>")
}

