// Code generated by gonx. DO NOT EDIT.

package pages

import (
	"io"
	"net/http"
)

func RenderHelloGonx(w io.Writer) {
	io.WriteString(w, "<div class=\"text-center py-12\">\n\t\t<h1 class=\"text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600 mb-6\">\n\t\t\tGo Framework\n\t\t</h1>\n\t\t<p class=\"text-xl text-gray-600 mb-10 max-w-2xl mx-auto\">\n\t\t\tFramework web Nuxt-like em <strong>Go + HTMX + TailwindCSS</strong>. \n\t\t\tZero-config, hot-reload, file-based routing.\n\t\t</p>\n\t\t<div class=\"grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl mx-auto mb-12\">\n\t\t\t<div class=\"block p-6 bg-white rounded-xl shadow-md border border-gray-100 text-left\">\n\t\t\t\t<h3 class=\"text-lg font-semibold text-gray-900 mb-2\">HTMX Demo</h3>\n\t\t\t\t<p class=\"text-gray-500 text-sm mb-3\">Clique para chamar a API via HTMX:</p>\n\t\t\t\t<button\n\t\t\t\t\thx-get=\"/api/hello\"\n\t\t\t\t\thx-target=\"#result\"\n\t\t\t\t\thx-swap=\"innerHTML\"\n\t\t\t\t\tclass=\"bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded-lg transition w-full\"\n\t\t\t\t>\n\t\t\t\t\tChamar API\n\t\t\t\t</button>\n\t\t\t\t<div id=\"result\" class=\"mt-3 p-3 bg-gray-50 rounded-lg text-sm text-gray-700 font-mono\"></div>\n\t\t\t</div>\n\t\t\t<div class=\"block p-6 bg-white rounded-xl shadow-md border border-gray-100 text-left\">\n\t\t\t\t<h3 class=\"text-lg font-semibold text-gray-900 mb-2\">API JSON</h3>\n\t\t\t\t<p class=\"text-gray-500 text-sm mb-3\">Resposta JSON da API:</p>\n\t\t\t\t<div class=\"p-3 bg-gray-900 text-green-400 rounded-lg text-xs font-mono overflow-x-auto\">\n\t\t\t\t\tGET /api/hello {\"message\":\"Hello from API\"}\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t\t<div class=\"text-sm text-gray-400\">\n\t\t\t<p>Hot-reload ativo Edite qualquer arquivo .go, .templ ou .css</p>\n\t\t</div>\n\t</div>")
}

func HelloGonx(w http.ResponseWriter, r *http.Request) {
	RenderHelloGonx(w)
}

