// Code generated by gonx. DO NOT EDIT.

package user

import (
	"io"
	"fmt"
	"html"
	"github.com/gofiber/fiber/v2"
	"playground/gonx/app/layouts"
)

func RenderIndex(w io.Writer, c *fiber.Ctx) {
	io.WriteString(w, "<div class=\"text-center py-12\">\n\t<h1 class=\"text-4xl font-bold text-gray-900 mb-4\">Usuário</h1>\n\t<p class=\"text-xl text-gray-600\">ID: <span class=\"font-mono text-blue-600\">")
	io.WriteString(w, html.EscapeString(fmt.Sprintf("%v", c.Params("id"))))
	io.WriteString(w, "</span></p>\n\t<a href=\"/\" class=\"mt-6 inline-block text-blue-600 hover:text-blue-800 underline\">Voltar</a>\n</div>")
}

func Index(c *fiber.Ctx) error {
	w := c.Response().BodyWriter()
	c.Set("Content-Type", "text/html; charset=utf-8")
	layouts.RenderIndex(w, "Go Framework", func(w io.Writer) {
		RenderIndex(w, c)
	})
	return nil
}

