package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go_template/pkg/router"
)

// Generate cria o arquivo .framework/routes.gen.go com base nas rotas descobertas
func Generate(root string, routes []router.Route) error {
	if len(routes) == 0 {
		return nil
	}

	outDir := filepath.Join(root, "gonx", "framework_gen")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	outPath := filepath.Join(outDir, "routes.gen.go")

	// Agrupa imports por package path
	importMap := make(map[string]string)
	for _, r := range routes {
		pkgAlias := aliasFromPath(r.PackagePath)
		importMap[r.PackagePath] = pkgAlias
	}

	var imports []string
	for path, alias := range importMap {
		imports = append(imports, fmt.Sprintf("\t%s \"%s\"", alias, path))
	}
	sort.Strings(imports)

	// Ordena rotas para determinismo e prioridade (estáticas antes de dinâmicas)
	sort.Slice(routes, func(i, j int) bool {
		pi := routes[i].Pattern
		pj := routes[j].Pattern
		
		// Se uma tem parâmetro e a outra não, a estática ganha
		hasParamI := strings.Contains(pi, ":")
		hasParamJ := strings.Contains(pj, ":")
		
		if hasParamI != hasParamJ {
			return !hasParamI // i ganha se NÃO tem parâmetro
		}
		
		// Se ambas têm ou não, ordena por profundidade (mais profunda primeiro?)
		// Na verdade, Fiber lida bem se as estáticas vierem antes.
		return pi+routes[i].Method < pj+routes[j].Method
	})

	var regLines []string
	for _, r := range routes {
		alias := importMap[r.PackagePath]
		pattern := r.Pattern
		// Fiber não precisa do {$} para rotas exatas, ele é padrão se não houver curingas
		
		method := strings.Title(strings.ToLower(r.Method))
		line := fmt.Sprintf("\trouter.%s(\"%s\", %s.%s)", method, pattern, alias, r.HandlerName)
		regLines = append(regLines, line)
	}

	// Handler catch-all para rotas nao encontradas
	regLines = append(regLines, "\trouter.Use(NotFound)")

	content := fmt.Sprintf(`// Code generated by framework. DO NOT EDIT.

package framework

import (
	"github.com/gofiber/fiber/v2"
%s
)

func RegisterRoutes(router *fiber.App) {
%s
}

func NotFound(c *fiber.Ctx) error {
	c.Status(fiber.StatusNotFound)
	c.Set("Content-Type", "text/html; charset=utf-8")
	return c.SendString(`+"`"+`<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>404 - Pagina nao encontrada</title>
	<style>
		* { margin: 0; padding: 0; box-sizing: border-box; }
		body {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
			font-family: system-ui, -apple-system, sans-serif;
			background: #ffffff;
			color: #1f2937;
		}
		.container { text-align: center; }
		.container h1 { font-size: 6rem; font-weight: 700; color: #e5e7eb; margin-bottom: 1rem; }
		.container p { font-size: 1.25rem; color: #6b7280; }
	</style>
</head>
<body>
	<div class="container">
		<h1>404</h1>
		<p>Pagina nao encontrada</p>
	</div>
</body>
</html>`+"`"+`)
}
`, strings.Join(imports, "\n"), strings.Join(regLines, "\n"))

	// Só reescreve se o conteúdo mudou (evita loops do watcher)
	if existing, err := os.ReadFile(outPath); err == nil && string(existing) == content {
		return nil
	}

	return os.WriteFile(outPath, []byte(content), 0644)
}

func aliasFromPath(path string) string {
	// Se for path de .gonx, cria alias distinto para evitar conflito
	if strings.Contains(path, "/gonx/") {
		parts := strings.Split(path, "/")
		var segs []string
		for i, p := range parts {
			if p == "gonx" && i+1 < len(parts) {
				segs = parts[i+1:]
				break
			}
		}
		alias := strings.Join(segs, "_")
		alias = strings.ReplaceAll(alias, "-", "_")
		alias = strings.ReplaceAll(alias, ".", "_")
		alias = strings.TrimPrefix(alias, "_")
		if len(alias) > 0 && alias[0] >= '0' && alias[0] <= '9' {
			alias = "_" + alias
		}
		return "gonx_" + alias
	}

	// Cria um alias válido baseado no último segmento do path
	parts := strings.Split(path, "/")
	alias := parts[len(parts)-1]

	// Sanitiza para identificador Go válido
	alias = strings.ReplaceAll(alias, "-", "_")
	alias = strings.ReplaceAll(alias, ".", "_")
	alias = strings.ReplaceAll(alias, "[", "")
	alias = strings.ReplaceAll(alias, "]", "")

	// Remove underscore inicial (parâmetros dinâmicos: _id -> id)
	alias = strings.TrimPrefix(alias, "_")

	// Se começar com dígito, prefixa com underscore
	if len(alias) > 0 && alias[0] >= '0' && alias[0] <= '9' {
		alias = "_" + alias
	}

	return alias
}
