package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go_template/pkg/router"
)

// Generate cria o arquivo .framework/routes.gen.go com base nas rotas descobertas
func Generate(root string, routes []router.Route) error {
	if len(routes) == 0 {
		return nil
	}

	outDir := filepath.Join(root, ".framework")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	outPath := filepath.Join(outDir, "routes.gen.go")

	// Agrupa imports por package path
	importMap := make(map[string]string)
	for _, r := range routes {
		pkgAlias := aliasFromPath(r.PackagePath)
		importMap[r.PackagePath] = pkgAlias
	}

	var imports []string
	for path, alias := range importMap {
		imports = append(imports, fmt.Sprintf("\t%s \"%s\"", alias, path))
	}
	sort.Strings(imports)

	// Ordena rotas para determinismo
	sort.Slice(routes, func(i, j int) bool {
		return routes[i].Pattern+routes[i].Method < routes[j].Pattern+routes[j].Method
	})

	var regLines []string
	for _, r := range routes {
		alias := importMap[r.PackagePath]
		line := fmt.Sprintf("\tmux.HandleFunc(\"%s %s\", %s.%s)", r.Method, r.Pattern, alias, r.HandlerName)
		regLines = append(regLines, line)
	}

	content := fmt.Sprintf(`// Code generated by framework. DO NOT EDIT.

package framework

import (
	"net/http"
%s
)

func RegisterRoutes(mux *http.ServeMux) {
%s
}
`, strings.Join(imports, "\n"), strings.Join(regLines, "\n"))

	// Só reescreve se o conteúdo mudou (evita loops do watcher)
	if existing, err := os.ReadFile(outPath); err == nil && string(existing) == content {
		return nil
	}

	return os.WriteFile(outPath, []byte(content), 0644)
}

func aliasFromPath(path string) string {
	// Cria um alias único baseado no último segmento do path
	parts := strings.Split(path, "/")
	alias := parts[len(parts)-1]
	// Remove caracteres inválidos para identificador
	alias = strings.ReplaceAll(alias, "-", "_")
	alias = strings.ReplaceAll(alias, ".", "_")
	return alias
}
