package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go_template/pkg/router"
)

// Generate cria o arquivo .framework/routes.gen.go com base nas rotas descobertas
func Generate(root string, routes []router.Route) error {
	if len(routes) == 0 {
		return nil
	}

	outDir := filepath.Join(root, "framework_gen")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	outPath := filepath.Join(outDir, "routes.gen.go")

	// Agrupa imports por package path
	importMap := make(map[string]string)
	for _, r := range routes {
		pkgAlias := aliasFromPath(r.PackagePath)
		importMap[r.PackagePath] = pkgAlias
	}

	var imports []string
	for path, alias := range importMap {
		imports = append(imports, fmt.Sprintf("\t%s \"%s\"", alias, path))
	}
	sort.Strings(imports)

	// Ordena rotas para determinismo
	sort.Slice(routes, func(i, j int) bool {
		return routes[i].Pattern+routes[i].Method < routes[j].Pattern+routes[j].Method
	})

	var regLines []string
	for _, r := range routes {
		alias := importMap[r.PackagePath]
		line := fmt.Sprintf("\tmux.HandleFunc(\"%s %s\", %s.%s)", r.Method, r.Pattern, alias, r.HandlerName)
		regLines = append(regLines, line)
	}

	content := fmt.Sprintf(`// Code generated by framework. DO NOT EDIT.

package framework

import (
	"net/http"
%s
)

func RegisterRoutes(mux *http.ServeMux) {
%s
}
`, strings.Join(imports, "\n"), strings.Join(regLines, "\n"))

	// Só reescreve se o conteúdo mudou (evita loops do watcher)
	if existing, err := os.ReadFile(outPath); err == nil && string(existing) == content {
		return nil
	}

	return os.WriteFile(outPath, []byte(content), 0644)
}

func aliasFromPath(path string) string {
	// Se for path de .gonx, cria alias distinto para evitar conflito
	if strings.Contains(path, "/gonx/") {
		parts := strings.Split(path, "/")
		var segs []string
		for i, p := range parts {
			if p == "gonx" && i+1 < len(parts) {
				segs = parts[i+1:]
				break
			}
		}
		alias := strings.Join(segs, "_")
		alias = strings.ReplaceAll(alias, "-", "_")
		alias = strings.ReplaceAll(alias, ".", "_")
		alias = strings.TrimPrefix(alias, "_")
		if len(alias) > 0 && alias[0] >= '0' && alias[0] <= '9' {
			alias = "_" + alias
		}
		return "gonx_" + alias
	}

	// Cria um alias válido baseado no último segmento do path
	parts := strings.Split(path, "/")
	alias := parts[len(parts)-1]

	// Sanitiza para identificador Go válido
	alias = strings.ReplaceAll(alias, "-", "_")
	alias = strings.ReplaceAll(alias, ".", "_")
	alias = strings.ReplaceAll(alias, "[", "")
	alias = strings.ReplaceAll(alias, "]", "")

	// Remove underscore inicial (parâmetros dinâmicos: _id -> id)
	alias = strings.TrimPrefix(alias, "_")

	// Se começar com dígito, prefixa com underscore
	if len(alias) > 0 && alias[0] >= '0' && alias[0] <= '9' {
		alias = "_" + alias
	}

	return alias
}
