// Code generated by framework. DO NOT EDIT.

package framework

import (
	"net/http"
	api "go_template/app/api"
	gonx_app_pages "go_template/gonx/app/pages"
)

func RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /", gonx_app_pages.Index)
	mux.HandleFunc("GET /api/hello", api.GetHello)
}
