// Code generated by framework. DO NOT EDIT.

package framework

import (
	"net/http"
	api "go_template/app/api"
	gonx_app_api "go_template/gonx/app/api"
	gonx_app_api_users "go_template/gonx/app/api/users"
	gonx_app_pages "go_template/gonx/app/pages"
	gonx_app_pages_dashboard "go_template/gonx/app/pages/dashboard"
)

func RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /", gonx_app_pages.Index)
	mux.HandleFunc("GET /api/hello", api.GetHello)
	mux.HandleFunc("GET /api/users/edit", gonx_app_api_users.GetUsersEdit)
	mux.HandleFunc("DELETE /api/users", gonx_app_api.DeleteUsers)
	mux.HandleFunc("GET /api/users", gonx_app_api.GetUsersSearch)
	mux.HandleFunc("POST /api/users", gonx_app_api.PostUsers)
	mux.HandleFunc("PUT /api/users", gonx_app_api.PutUsers)
	mux.HandleFunc("GET /dashboard/form", gonx_app_pages_dashboard.Form)
	mux.HandleFunc("GET /dashboard", gonx_app_pages.Dashboard)
}
